# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-23 06:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookinginfomation',
            name='seat',
            field=models.CharField(default=None, max_length=10, verbose_name='Seat'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bookinginfomation',
            name='time_showing',
            field=models.TimeField(default=django.utils.timezone.now, verbose_name='Time Show'),
            preserve_default=False,
        ),
    ]
