# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-24 07:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_auto_20171023_1353'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovieSync',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modified Date')),
                ('name', models.CharField(choices=[('movie_comming', 'Movie Comming Soon'), ('movie_showing', 'Movie Showing'), ('showtime_current', 'Show Times')], max_length=50)),
                ('cinema_id', models.IntegerField(default=1)),
                ('area_id', models.IntegerField(default=0)),
                ('data', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
