# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-24 08:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_moviesync'),
    ]

    operations = [
        migrations.AddField(
            model_name='moviesync',
            name='date_show',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Date Showing'),
            preserve_default=False,
        ),
    ]
