# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-11-02 04:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_moviesync_date_show'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookinginfomation',
            name='seat',
        ),
        migrations.AddField(
            model_name='bookinginfomation',
            name='barcode',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='bookinginfomation',
            name='seats',
            field=models.CharField(default=None, max_length=10, verbose_name='Seats'),
            preserve_default=False,
        ),
    ]
