# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-11-02 04:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_auto_20171102_1115'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookinginfomation',
            name='movie',
        ),
        migrations.RemoveField(
            model_name='bookinginfomation',
            name='time_showing',
        ),
        migrations.AddField(
            model_name='bookinginfomation',
            name='order_desc',
            field=models.TimeField(default=None, verbose_name='Description'),
            preserve_default=False,
        ),
    ]
