# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-11-02 04:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_auto_20171102_1126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinginfomation',
            name='order_desc',
            field=models.TextField(verbose_name='Description'),
        ),
    ]
