# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-11-02 04:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0007_auto_20171102_1128'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookinginfomation',
            name='id_server',
            field=models.IntegerField(default=1),
        ),
    ]
