# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-11-02 04:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0008_bookinginfomation_id_server'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinginfomation',
            name='seats',
            field=models.TextField(verbose_name='Seats'),
        ),
    ]
