# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-11-02 07:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0009_auto_20171102_1143'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookinginfomation',
            name='order_status',
            field=models.CharField(choices=[('pendding', 'Pendding'), ('done', 'Done')], default='pendding', max_length=50),
        ),
    ]
