# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-11-02 09:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0010_bookinginfomation_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookinginfomation',
            name='barcode_confirm',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
