# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-11-06 09:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0011_bookinginfomation_barcode_confirm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinginfomation',
            name='order_status',
            field=models.CharField(choices=[('cancel', 'Cancel'), ('pendding', 'Pendding'), ('done', 'Done')], default='pendding', max_length=50),
        ),
    ]
