# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-01-29 02:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0014_auto_20180112_1027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinginfomation',
            name='order_status',
            field=models.CharField(choices=[('cancel', 'Cancel'), ('confirm_error', 'Confirm Error'), ('payment_error', 'Payment Error'), ('pendding', 'Pendding'), ('done', 'Done')], default='pendding', max_length=50),
        ),
    ]
