# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-06-06 08:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0015_auto_20180129_0927'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookinginfomation',
            name='card_barcode',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Card Barcode'),
        ),
        migrations.AddField(
            model_name='bookinginfomation',
            name='gate_payment',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Gate Payment'),
        ),
        migrations.AddField(
            model_name='bookinginfomation',
            name='poster',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
