# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-06-15 08:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0016_auto_20180606_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinginfomation',
            name='gate_payment',
            field=models.CharField(blank=True, choices=[('VNPay', 'VNPay'), ('Helio_Payment_Card', 'Helio Payment Card'), ('Metiz_Payment_Card', 'Metiz Payment Card')], max_length=500, null=True, verbose_name='Gate Payment'),
        ),
    ]
