# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-06-21 09:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0017_auto_20180615_1558'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookinginfomation',
            name='working_id',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Working Id'),
        ),
    ]
