# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-06-29 08:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0018_bookinginfomation_working_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookinginfomation',
            name='card_member',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Card Member'),
        ),
        migrations.AddField(
            model_name='bookinginfomation',
            name='point_bonus',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bookinginfomation',
            name='point_level',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='bookinginfomation',
            name='card_barcode',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Card Barcode Payment'),
        ),
    ]
