# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-23 09:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0019_auto_20180629_1520'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookinginfomation',
            name='system_name',
            field=models.CharField(blank=True, choices=[('metiz_online', 'Metiz Web Online'), ('metiz_app', 'Metiz App')], default='metiz_online', max_length=500, null=True, verbose_name='System Name'),
        ),
    ]
