# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-27 08:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modified Date')),
                ('full_name', models.CharField(max_length=100)),
                ('avatar', models.ImageField(blank=True, max_length=500, null=True, upload_to='comment_avatar')),
                ('review', models.TextField()),
                ('rating', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=5)),
                ('date_post', models.DateField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='genre',
            name='description',
        ),
        migrations.RemoveField(
            model_name='rated',
            name='icon',
        ),
        migrations.AddField(
            model_name='rated',
            name='description',
            field=models.TextField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cenimatechnology',
            name='name',
            field=models.CharField(choices=[('4d', '4DX'), ('sweetbox', 'SWEETBOX'), ('dolby_atmos', 'DOLBY ATMOS'), ('imax', 'IMAX'), ('gold_class', 'GOLD CLASS'), ('lamour', 'LAMOUR'), ('starium', 'STARIUM'), ('premium_cinema', 'PREMIUN CENIMA'), ('screen_x', 'SCREEN X')], max_length=50),
        ),
    ]
