# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-02 03:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20170927_0821'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='movie',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='movie_comment_rel', to='core.Movie'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='banner',
            name='position',
            field=models.IntegerField(choices=[(1, 1), (2, 2)]),
        ),
        migrations.AlterField(
            model_name='cenimatechnology',
            name='name',
            field=models.CharField(choices=[('4dx', '4DX'), ('sweetbox', 'SWEETBOX'), ('dolby-atmos', 'DOLBY ATMOS'), ('imax', 'IMAX'), ('gold-class', 'GOLD CLASS'), ('lamour', 'LAMOUR'), ('starium', 'STARIUM'), ('premium', 'PREMIUN CENIMA'), ('screenx', 'SCREEN X')], max_length=50),
        ),
    ]
