# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-03 06:58
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20171003_0653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newoffer',
            name='apply_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
