# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-03 10:03
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20171003_0658'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='banner',
            options={'verbose_name': 'Banner'},
        ),
        migrations.AlterModelOptions(
            name='cenimatechnology',
            options={'verbose_name': 'Cenima Technology', 'verbose_name_plural': 'Cenima Technologys'},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': 'Comment', 'verbose_name_plural': 'Comments'},
        ),
        migrations.AlterModelOptions(
            name='genre',
            options={'verbose_name': 'Genre', 'verbose_name_plural': 'Genres'},
        ),
        migrations.AlterModelOptions(
            name='movie',
            options={'verbose_name': 'Movie', 'verbose_name_plural': 'Movies'},
        ),
        migrations.AlterModelOptions(
            name='movietype',
            options={'verbose_name': 'Movie Type', 'verbose_name_plural': 'Movie Types'},
        ),
        migrations.AlterModelOptions(
            name='newoffer',
            options={'verbose_name': 'New Offer', 'verbose_name_plural': 'New Offers'},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name': 'Post', 'verbose_name_plural': 'Posts'},
        ),
        migrations.AlterModelOptions(
            name='rated',
            options={'verbose_name': 'Rated'},
        ),
        migrations.AlterModelOptions(
            name='slideshow',
            options={'verbose_name': 'Slide Show'},
        ),
        migrations.AlterField(
            model_name='banner',
            name='image',
            field=models.ImageField(max_length=1000, upload_to='banners', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='is_show',
            field=models.BooleanField(default=False, verbose_name='Is Show'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='position',
            field=models.IntegerField(choices=[(1, 1), (2, 2)], verbose_name='Position'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='sub_url',
            field=models.CharField(max_length=1000, verbose_name='Sub Url'),
        ),
        migrations.AlterField(
            model_name='cenimatechnology',
            name='content',
            field=models.TextField(verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='cenimatechnology',
            name='name',
            field=models.CharField(choices=[('4dx', '4DX'), ('sweetbox', 'SWEETBOX'), ('dolby-atmos', 'DOLBY ATMOS'), ('imax', 'IMAX'), ('gold-class', 'GOLD CLASS'), ('lamour', 'LAMOUR'), ('starium', 'STARIUM'), ('premium', 'PREMIUN CENIMA'), ('screenx', 'SCREEN X')], max_length=50, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='avatar',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to='comment_avatar', verbose_name='Avatar'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date_post',
            field=models.DateField(verbose_name='Date Post'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='full_name',
            field=models.CharField(max_length=100, verbose_name='Full Name'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='rating',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=5, verbose_name='Rating'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='review',
            field=models.TextField(verbose_name='Review'),
        ),
        migrations.AlterField(
            model_name='genre',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Name Genre'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='cast',
            field=models.CharField(max_length=255, verbose_name='Cast'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='description',
            field=models.TextField(verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='director',
            field=models.CharField(max_length=255, verbose_name='Director'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='language',
            field=models.CharField(max_length=255, verbose_name='Language'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Movie Name'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='priority',
            field=models.IntegerField(blank=True, null=True, verbose_name='Priority'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='release_date',
            field=models.DateField(verbose_name='Release Date'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='trailer',
            field=models.CharField(max_length=500, verbose_name='Trailer'),
        ),
        migrations.AlterField(
            model_name='movietype',
            name='name',
            field=models.CharField(choices=[('', '----'), ('2d', '2D'), ('3d', '3D'), ('4dx', '4DX'), ('imax', 'IMAX'), ('screenx', 'SCREEN X')], max_length=50, verbose_name='Type Name'),
        ),
        migrations.AlterField(
            model_name='newoffer',
            name='apply_date',
            field=models.DateField(default=datetime.date.today, verbose_name='Apply Date'),
        ),
        migrations.AlterField(
            model_name='newoffer',
            name='apply_for',
            field=models.CharField(choices=[('all', 'ALL'), ('member', 'Member')], default='all', max_length=50, verbose_name='Apply For'),
        ),
        migrations.AlterField(
            model_name='newoffer',
            name='condition',
            field=models.TextField(blank=True, null=True, verbose_name='Condition'),
        ),
        migrations.AlterField(
            model_name='newoffer',
            name='content',
            field=models.TextField(blank=True, null=True, verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='newoffer',
            name='image',
            field=models.ImageField(max_length=255, upload_to='new_offer', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='newoffer',
            name='movies',
            field=models.ManyToManyField(blank=True, to='core.Movie'),
        ),
        migrations.AlterField(
            model_name='newoffer',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='newoffer',
            name='priority',
            field=models.IntegerField(blank=True, null=True, verbose_name='Priority'),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='post',
            name='key_query',
            field=models.CharField(max_length=255, unique=True, verbose_name='Key Query'),
        ),
        migrations.AlterField(
            model_name='post',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='rated',
            name='description',
            field=models.TextField(max_length=255, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='rated',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='slideshow',
            name='image',
            field=models.ImageField(max_length=255, upload_to='slide_home', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='slideshow',
            name='priority',
            field=models.IntegerField(blank=True, null=True, verbose_name='Priority'),
        ),
    ]
