# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-06 08:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20171005_0956'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='is_draff',
            new_name='is_draft',
        ),
    ]
