# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-13 08:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20171006_0825'),
    ]

    operations = [
        migrations.AddField(
            model_name='slideshow',
            name='sub_url',
            field=models.CharField(default=None, max_length=1000, verbose_name='Sub Url'),
            preserve_default=False,
        ),
    ]
