# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-20 09:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20171020_1548'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='end_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='End Date'),
            preserve_default=False,
        ),
    ]
