# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-11-16 09:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='date_post',
            field=models.DateTimeField(verbose_name='Date Post'),
        ),
    ]
