# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-11-20 09:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20171116_1606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='subject',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
