# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-11-21 04:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20171120_1604'),
        ('core', '0017_newoffer_end_date'),
    ]

    operations = [
    ]
