# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-11-23 09:34
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_newoffer_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newoffer',
            name='end_date',
            field=models.DateField(blank=True, default=datetime.date.today, null=True, verbose_name='End Date'),
        ),
    ]
