# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-11-28 07:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_auto_20171123_1634'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='genre',
        ),
        migrations.AddField(
            model_name='movie',
            name='genre',
            field=models.ManyToManyField(related_name='film_genre_rel', to='core.Genre'),
        ),
    ]
