# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-13 03:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_auto_20171128_1459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newoffer',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='post',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Name'),
        ),
    ]
