# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-29 09:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_blog'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'verbose_name': 'Blog Film', 'verbose_name_plural': 'Blog Film'},
        ),
    ]
