# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-01-30 07:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_voucher'),
    ]

    operations = [
        migrations.AddField(
            model_name='admininfo',
            name='email_type',
            field=models.CharField(choices=[('to', 'To'), ('cc', 'cc')], default='to', max_length=50, verbose_name='Email Type'),
        ),
    ]
