# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-03-09 10:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_admininfo_email_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='End Date'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='rated',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='film_rated_rel', to='core.Rated'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='time_running',
            field=models.IntegerField(blank=True, null=True, verbose_name='Time Running'),
        ),
    ]
