# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-06-04 03:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_auto_20180601_0959'),
    ]

    operations = [
        migrations.CreateModel(
            name='Home_Ads',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modified Date')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Name')),
                ('image', models.ImageField(max_length=1000, upload_to='home_ads', verbose_name='Image')),
                ('is_show', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Home Ads',
                'verbose_name_plural': 'Home Ads',
            },
        ),
    ]
