# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-06-04 04:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_home_ads'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='home_ads',
            name='name',
        ),
        migrations.AddField(
            model_name='home_ads',
            name='sub_url',
            field=models.CharField(default='', max_length=1000, verbose_name='Sub url'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='home_ads',
            name='is_show',
            field=models.BooleanField(default=False, verbose_name='Is show'),
        ),
    ]
