# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-07-20 08:43
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_auto_20180604_1133'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favourite_Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modified Date')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movie_favourite_rel', to='core.Movie')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_favourite_movie_rel', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Favourite Movie',
                'verbose_name_plural': 'Favourite Movies',
            },
        ),
        migrations.CreateModel(
            name='Favourite_NewOffer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modified Date')),
                ('new', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='new_favourite_rel', to='core.NewOffer')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_favourite_new_rel', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Favourite New',
                'verbose_name_plural': 'Favourites News',
            },
        ),
    ]
