# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-26 07:44
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_favourite_movie_favourite_newoffer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255, unique=True, verbose_name='Subject')),
                ('message', models.TextField(verbose_name='Message')),
                ('image', models.ImageField(blank=True, max_length=1000, null=True, upload_to=b'', verbose_name='Image')),
                ('sub_url', models.CharField(blank=True, max_length=255, null=True, verbose_name='Sub url')),
                ('is_public', models.BooleanField(default=False)),
                ('sent_date', models.DateField(blank=True, null=True, verbose_name='Sent Date')),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notification',
            },
        ),
        migrations.CreateModel(
            name='UserIntermediate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_read', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='favourite_movie',
            unique_together=set([('user', 'movie')]),
        ),
        migrations.AlterUniqueTogether(
            name='favourite_newoffer',
            unique_together=set([('user', 'new')]),
        ),
        migrations.AddField(
            model_name='notification',
            name='users',
            field=models.ManyToManyField(related_name='notification_users', to='core.UserIntermediate'),
        ),
    ]
